server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://121.37.216.114:3306/service-passenger-user?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&serverTimezone=Asia/Shanghai
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        service: service-passenger-user